import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingHorizontal: 16, paddingTop: 12, gap: 12, paddingBottom: 72 },
  card: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 18,
    gap: 14,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  pretitleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  pretitle: { fontSize: 12, fontWeight: "700", letterSpacing: 0.6, textTransform: "uppercase" },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  statusText: { fontSize: 11, fontWeight: "800", letterSpacing: 0.3 },
  title: { fontSize: 24, fontWeight: "800", lineHeight: 30, letterSpacing: -0.2 },
  company: { fontSize: 14, fontWeight: "600" },
  metaRow: { flexDirection: "row", gap: 10 },
  metaChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  metaIconBox: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  metaLabel: { fontSize: 10, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.35 },
  metaValue: { fontSize: 13, fontWeight: "700", marginTop: 2 },
  sectionHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 2 },
  sectionIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  subheading: { fontSize: 16, fontWeight: "700" },
  row: { flexDirection: "row", gap: 10 },
  badge: { flex: 1, borderWidth: 1, borderRadius: 12, padding: 12, gap: 4 },
  badgeLabel: { fontSize: 12, fontWeight: "700" },
  badgeValue: { fontSize: 14, fontWeight: "700" },
  sectionCard: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 4 },
  fieldRow: { paddingVertical: 10, gap: 4 },
  fieldHeader: { flexDirection: "row", alignItems: "center", gap: 6 },
  fieldLabel: { fontSize: 12, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.5 },
  fieldValue: { fontSize: 15, fontWeight: "700" },
  rowDivider: { height: 1, width: "100%" },
  coverLetter: { borderWidth: 1, borderRadius: 12, padding: 12, gap: 6 },
  sectionHeaderSmall: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 2 },
  coverText: { fontSize: 14, lineHeight: 22, fontWeight: "500" },
  actions: { flexDirection: "row", gap: 10, marginTop: 8 },
  secondaryButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
  },
  secondaryText: { fontSize: 14, fontWeight: "700" },
  dangerButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
  },
  dangerText: { fontSize: 14, fontWeight: "800" },
  emptyWrapper: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, gap: 12 },
  emptyTitle: { fontSize: 20, fontWeight: "800" },
  emptySubtitle: { fontSize: 14, fontWeight: "500", textAlign: "center", lineHeight: 20 },
  backButton: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10 },
  backText: { fontSize: 14, fontWeight: "700" },
});
